$(document).ready(function(){
$(".design_image").click(function(){
$(this).hide()
$(".design").show()
});
$(".design").click(function(){
    $(this).hide()
    $(".design_image").show()
});
$(".dev_image").click(function(){
$(this).hide()
$(".development").show()
$(".development").click(function(){
$(this).hide()
$("dev_image").show()
});
});
$(".product_image").click(function(){
$(this).hide()
$(".product").show()
$(".product").click(function(){
$(this).hide()
$(".product_image").show()
});
});
});